default.graylog2[:basedir] = "/var/graylog2"
default.graylog2[:serverversion] = "0.9.4p1"
default.graylog2[:webuiversion] = "0.9.4p2"
default.graylog2[:collectionsize] = "50000000"
default.graylog2[:db_user] = "root"
default.graylog2[:db_pass] = ""
default.graylog2[:port] = "514"
default.graylog2[:protocol] = "tcp"